name: devil_scout
description: A FRC scouting app by Team 1559
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
