name: Build & Test for iOS and Android

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Setup Flutter environment
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Download packages
      run: flutter pub get

    - name: Run unit tests
      run: flutter test

  ios:
    runs-on: macos-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Setup Flutter environment
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Download packages
      run: flutter pub get

    - name: Build for iOS (release)
      run: flutter build ios --release --no-codesign

  android:
    runs-on: macos-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Flutter environment
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Download packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Build Android app bundle
      run: flutter build appbundle
